swagger:
  exclude-path: /error
  authorization:
    key-name: Authorization
    auth-regex: ^.*$
    name: Authorization
  ignored-parameter-types:
    - com.andy.core.bean.dto.UserInfoDTO

mysql:
  host: dnode20
  port: 3306
  username: teamdev
  password: TAdm1n;523

redis:
  host: dnode20
  port: 6379
  database: 0
