spring:
  redis:
    database: ${redis.database}
    host: ${redis.host}
    port: ${redis.port}
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

