server:
  port: 9003

spring:
  zipkin:
    base-url: http://zipkin:9006
  boot:
    admin:
      client:
        url: http://zipkin:9004
  # 获取本地配置文件，本身支持：本地储存、git远程、SVN
  profiles:
    active: dev

